# Keep the preload for performance
preload = ~/.config/backgrounds/nice-blue-background.png
splash = false
# New block syntax for Hyprpaper 0.8.0+
wallpaper {
    monitor =
    path = ~/.config/backgrounds/nice-blue-background.png
}
